---
- name: configure rabbitmq
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  notify:
    - restart rabbitmq-server
  when: rabbitmq_config is defined

- name: configure rabbitmq env
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
  notify:
    - restart rabbitmq-server
  when: rabbitmq_env_config is defined
