---
- name: include rabbitmq installation tasks
  include: "{{ ansible_os_family }}/install.yml"

- include: configure.yml

- include: configure-cluster.yml
  when: rabbitmq_cluster

# Flush handlers here, so the service start below only ensures
# that the service is started and we don't unnecessarily restart
# rabbitmq-server in the end
- name: flush handlers to restart rabbitmq-server if notified
  meta: flush_handlers

- name: start rabbitmq server
  service:
    name: rabbitmq-server
    enabled: True
    state: started

- include: vhosts.yml

- include: users.yml

- include: plugins.yml

- include: cluster.yml
  when: rabbitmq_cluster and rabbitmq_nodename != rabbitmq_cluster_master
