---
- name: add erlang solutions repository
  yum_repository:
    name: RabbitMq-Erlang
    description: "{{ ansible_distribution }} - RabbitMq Erlang package"
    baseurl: "https://dl.bintray.com/rabbitmq/rpm/erlang/20/el/{{ ansible_distribution_major_version }}"
    gpgcheck: True
    gpgkey: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc

- name: install erlang
  yum:
    name: erlang

- name: import rabbitmq rpm key
  rpm_key:
    key: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc

- name: download rabbitmq package
  get_url:
    url: "https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version.split('-')[0] }}/rabbitmq-server-{{ rabbitmq_version }}{% if rabbitmq_version | version_compare('3.6.6', '>=') %}.el{{ ansible_distribution_major_version }}{% endif %}.noarch.rpm"
    dest: "/usr/src/rabbitmq-server-{{ rabbitmq_version }}.rpm"

- name: install rabbitmq
  yum:
    name: "/usr/src/rabbitmq-server-{{ rabbitmq_version }}.rpm"
